POST localhost:8080/profile/create_user
Content-Type:application/json
Accept-Language: RU

{
  "name" : "Kamoliddin",
  "surname" : "Abdugafarov",
  "email" : "kamolabdugafarovv@gmail.com",
  "password" :"30102002"
}
